### ISSUE TITLE
Add 'text: changes only' and 'source: changes only'

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#102]
As discussed at 8/9/17 web dev meeting, we should include the above diffs for v0. At this time we just need a simple implementation with changes and providing some context around the change. 

I will try to tackle this to understand more how web-monitoring-processing works and how the UI gets the diffs from it.

**Comment by Mr0grog** [comment]
If it helps, you probably want to either make a separate component that is similar to [`HighlightedTextDiff`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/highlighted-text-diff.jsx) or add a prop to it specifying whether to show unchanged content. Then, where it renders the `List` component, you’d just pass a different array for the `data` prop.

**Comment by Mr0grog** [comment]
This was fixed in #105 and merged in 32cfc6287c6c3d8e63a2d3fdf4efcb219e5dccc8
