### ISSUE TITLE
Update record gives 500

### ISSUE THREAD

**Issue by lazywithclass** [edgi-govdata-archiving/web-monitoring-ui#109]
Whenever I click "update record" on what seems to be every record, I get this

> {"errors":[{"status":500,"title":"undefined method `change' for nil:NilClass"}]}

This blocks https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/107

**Comment by Mr0grog** [comment]
You have to always post *some* data (see https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/114, the “fix” would still return a `400` status error, it’ll have a better message, though). So the real change that needs to be made here is to either disable the button until some change to the annotation has been made or to make sure at least *something* is sent.

I think the correct approach is to probably make sure we always send the contents of the whole annotation form when the “update record” button is clicked. At present, we only send the fields that have *changed.* If you never clicked any of the annotation checkboxes, then nothing ever got changed. That’s probably wrong.

**Comment by Mr0grog** [comment]
So, more specifically, the [`onChange` callback in `AnnotationForm`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/annotation-form.jsx#L93-L98) should grab the value of every field in the form and send it, not just the values of the fields that have had `change` events so far.

**Comment by lazywithclass** [comment]
Ah whoops, sorry. I was convinced this to be a bug. Thanks for the detailed explanation!

**Comment by Mr0grog** [comment]
Yeah, it would be a lot more obvious if the API returned a more informative error, which that PR should fix :\
