### ISSUE TITLE
Show changes to a list of a page’s links

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#113]
From the analyst meeting on 2017-09-06: it would be helpful and not too complicated to show analysts a list of all the links on a page and highlight additions or removals. I figure we should de-duplicate and sort the list alphabetically (by URL) to keep comparisons simple (the focus is on additions/removals/changes, not where on the page these are or if they are repeated).

Posting this in UI for now as we could implement it here in a quick-n-dirty way just with the raw content from each page, but we could also implement in `web-monitoring-processing`, too.

/cc @danielballan

**Comment by danielballan** [comment]
I'm perfectly happy to do this on the processing side.

**Comment by Mr0grog** [comment]
👍 perfect, let’s do that, then.

**Comment by lightandluck** [comment]
Closing, as it was agreed to handle this in processing.

**Comment by Mr0grog** [comment]
I think we still need to keep this open as a task to *display* that diff, though.

**Comment by lightandluck** [comment]
Ah, true!
