### ISSUE TITLE
Look into using react-svg-inline or otherwise inlining SVG somehow

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#124]
This is a follow-on to #118 based on the notes from @garrying here: https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/122#issuecomment-330714272

Look into inlining our SVG graphics (just the loader right now), either using [`react-svg-inline`](https://www.npmjs.com/package/react-svg-inline) or something else. May require us to finally get our act together on #88 first.

**Comment by thecalliopecrashed** [comment]
Looks like this was created to handle the loading spinner animation bug, but that's been fixed.
Is there further motivation for this?

**Comment by Mr0grog** [comment]
Oops, didn’t realize this was never replied to. :(

> Looks like this was created to handle the loading spinner animation bug, but that's been fixed.

Actually, this was created to fix a bug with the fix. ;)
