### ISSUE TITLE
Add linting to CI

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#125]
Linting errors keep cropping up. We should add linting to CI so we are made aware of them in PRs.

**Comment by don-harris** [comment]
Howdy, I'll help with this one !

**Comment by Mr0grog** [comment]
Hey, @don-harris, this was just done a few days ago in #144. Sorry, I had thought this issue got closed.

**Comment by don-harris** [comment]
Hey @Mr0grog That's alright :) thanks for letting me know
