### ISSUE TITLE
Add links to versionista to diff view to enable cross-checking (for now)

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-ui#131]
Put this next to the Comparison select box. Obviously it will have to go away when we unplug Versionista. This is just to support bug-checking during the migration.

We will treat this as an escape hatch so that analysis can continue to do their jobs while we debug.

**Comment by Mr0grog** [comment]
A fancy version of this might not present the link unless the two versions are both either:
- The earliest Versionista version of the page
- One of the most recent 49 Versionista versions of the page

(Versionista only keep 50 versions of any given page; we generally have it set to always keep the original, but worth noting that got missed on a few pages.)

**Comment by danielballan** [comment]
Fancy or no, it would be good to give some indication to analysts that this is a temporary feature not expected to be 100% reliable. This could take the form of a UI element (like a tooltip) or just a verbal instruction.
