### ISSUE TITLE
Side-by-side rendered diffs should extend to the bottom of the screen

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#134]
On larger screens, you can easily wind up with a lot of wasted space at the bottom of the side-by-side diff that could be used to show more of the diffed pages:

![screen shot 2017-09-30 at 11 27 06 pm](https://user-images.githubusercontent.com/74178/31052347-05aa726c-a637-11e7-9e9b-56c68a4e65d7.png)

On smaller screens, it is is painful in the opposite way: the iframes for each page are scrollable, but so is the parent area, making it hard to find a layout that lets you see everything clearly.

Those diff views should either:

1. Simply take up all the remaining space between the version selector and the bottom of the screen, or
2. Dynamically resize the frames to fit the web pages they contain (probably by checking `document.documentElement.scrollHeight`), so instead of scrolling the frames, you scroll the whole page details page

**Comment by lightandluck** [comment]
@lazywithclass Sorry for the slow progress over here, but thought this might be an interesting issue, if you have time to tackle it. Option 2 might be more difficult, but preferred. 

There are also new issues in the repo. Let me know if any interest you instead. Thanks!

**Comment by Mr0grog** [comment]
FWIW, if we took option 2, we might want to make the form and other controls at the top `position: fixed` or `sticky` or something similar (sorry to be piling on the complexity here).

**Comment by lightandluck** [comment]
Agreed, that would be useful.

**Comment by lazywithclass** [comment]
@lightandluck sure! I will give it a go in the weekend.

**Comment by lightandluck** [comment]
@lazywithclass Great to hear! I'm visiting family this weekend, so might not have a chance to review or help out until next week. Please ping @Mr0grog or @danielballan if you need to ask any questions. Looking forward to what you come up with! I've tried to tackle this briefly in the past and never could get something to stick.

**Comment by lazywithclass** [comment]
I didn't manage to have something working, I've noticed that the empty area at the bottom is excluded from `body`, I don't know if that's a glitch in chrome dev tools or what. I will give it another go this week, but it seems a tough problem, especially for someone not CSS proficient like me :D

**Comment by lightandluck** [comment]
@lazywithclass Sorry, for the late response, but had to deal with a personal emergency.

You might want to look in `diff.css` where the height of the iframes are set and maybe use flexbox to size them instead. None of those styles are set in stone, so feel free to change them as needed to get things working. 

Also, to get the content of the iframes and set them programmatically, you could try using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) from the iframes. 

If you find you don't have the time to tackle this, please let me know so I can divert my attention back to it. Don't be shy to submit a WIP PR that we can iterate on together if necessary. 😉

**Comment by lazywithclass** [comment]
@lightandluck I will give it another go in the upcoming weekend.

**Comment by Mr0grog** [comment]
@lazywithclass did you get anything done on this? Just checking in.

**Comment by lazywithclass** [comment]
@Mr0grog I tried again in various moments in the last couple of weeks but without any real progress, the idea is to give it another go in the next days, if I'll fail again I'll have to pass on this

**Comment by Mr0grog** [comment]
@lazywithclass OK. Please post back here and let us know where you do or don’t get on this; it’s kind of high priority, so we need to know someone else like me or @lightandluck should start working on it if you decide not to.

**Comment by lazywithclass** [comment]
@Mr0grog I've tried again but without any success, I focused on trying to have a CSS solutions but it didn't work. I don't want to stop your progress anymore, so I say I move away from this, but will try again on my own, I will surely post here if I get onto something.

**Comment by Mr0grog** [comment]
@lazywithclass Ok, thanks for the update.
