### ISSUE TITLE
Add route for a single version

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#145]
Analysts have access to version IDs, so it would be nice if there was an easy way for them to navigate directly to that version in the UI using that ID. We’ll eventually have nicer links for them, but I think this would be a useful behavior, regardless.

I’m thinking this route would just be a redirect, e.g. if you navigate to:

```
/version/85f35fdb-3d5e-47cb-bd8e-f489e5653002
    ⤷ redirects to… ⤵︎
/page/de3caafd-c8bb-4fe6-b9ac-0c8684800136/..85f35fdb-3d5e-47cb-bd8e-f489e5653002
```

**Comment by lightandluck** [comment]
+1 Very good suggestion
