### ISSUE TITLE
Add fallback for Intl api

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#155]
We're using `Intl`, a newer api, for date formatting. If it doesn't exist the app breaks. 

For possible resolutions, excerpted from last part of this [comment](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/154#discussion_r153136815).

> >I'm getting this error: ReferenceError: Can't find variable: Intl in my version of Safari (9.1.3), so I can't get the app to load at all which is why I haven't been seeing them. Looks like it's a API that doesn't exist in my old version. How should we go about polyfilling that?
> 
> So… there are probably a lot more things broken when you go back back more than two major releases. We haven’t really been doing the work to support anything that old. But either way, you could polyfill using https://www.npmjs.com/package/intl . I would just skip it, though. Our date formatting isn’t that critical, I think, so you could just replace it with a call to date.toLocaleString() if Intl is not present.

**Comment by Mr0grog** [comment]
To do this, we basically need to set [`dateFormatter` in `src/scripts/formatters.js`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/scripts/formatters.js#L3-L11) depending on whether `window.Intl && window.Intl.DateTimeFormat` exists.

**Comment by Mr0grog** [comment]
Fixed by @marlungu in PR #229, commit a57ebd50cb1c844fb33f60f378890dce16ca1601
