### ISSUE TITLE
When no pages are assigned, spinner shows endlessly

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#167]
If an analyst doesn't have any pages assigned to them, the endless spinner is displayed.

Suggested solution:
Show message: You are not assigned to any pages.

Also, what happens if no diffs were found to assigned pages?

**Comment by Mr0grog** [comment]
Fixed in #177, merged to master in e5b02589a96877d2b830b3f6c82e5528f1f2819e
