### ISSUE TITLE
Update ESLint to check for new UI practices

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#170]
~DO NOTE MERGE UNTIL Contributor pages has been updated.
https://github.com/edgi-govdata-archiving/web-monitoring/issues/81~

Update ESLint to test for the UI practices in the web-monitor and web-monitoring-ui repo contributor.md pages.

https://github.com/edgi-govdata-archiving/web-monitoring/blob/master/CONTRIBUTING.md
https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/CONTRIBUTING.md

From Issue 81 on web-monitor repo:
"e.g. spacing, alphabetization, ES* features, browser features. I think there is a React plug-in for ESLint that may have optional rules for things like prop types (https://www.npmjs.com/package/eslint-plugin-react)"

**Comment by geekyatri** [comment]
Is this still open @lightandluck  @weatherpattern

**Comment by lightandluck** [comment]
Hi @geekyatri!
Yes, it is 👍
