### ISSUE TITLE
Get analysts input to expand `Latest-to-base` functionality beyond Versionista

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#173]
Moving the conversation from #168 and setting aside spacetime to get more input from analysts.

**Comment by lightandluck** [comment]
Mr0grog -
> As we start pulling in archive.org data, “base” could mean a version as far back as the 1990’s. I think the way analysts use “base” is really about “end of previous administration,” though. Since that’s when we started tracking things in Versionista, “base” is a convenient stand-in that will no longer make sense with more historic data.

**Comment by lightandluck** [comment]
lightandluck - 
>That's also my understanding that
>>“base” is really about “end of previous administration,”

>For now while we're still using Versionista, I think it's useful for new analysts to be able to jump there quickly as they're understanding the history of how a site has changed since that particular point. Ray has mentioned he used that link in the spreadsheets when he first started. But in the app, it should probably be temporary like the versionista-infolink for the reasons Mr0grog mentioned.

>After thinking about it a bit, maybe the ability to bookmark any version and be able to compare that bookmark quickly with the latest version might be what we want to do in the future with all the different incoming sources? You could have multiple bookmarks like "Obama administration", "Clinton", "End of EPA Act XXXX", etc. This could be the precursor to that?

**Comment by lightandluck** [comment]
danielballan -
>"Latest to base" has always seemed unsustainable to me over the long haul, as our diffing tools are optimized to make incremental changes comprehensible. Looking at changes over very long periods will degrade. I think lightandluck makes a fair point that this is a good temporary feature to smooth over the transition, and I would be fine with merging it if we are solidly agreed that we intend to remove it in the future, in favor of 'latest to 2016', 'latest to ~6 months ago', etc. My only (small) concern is that we'll get some push back from analysts when we try to remove the familiar "latest to base" feature later if we don't do it now.

**Comment by lightandluck** [comment]
Mr0grog -
>For my part, I see this as different from the temporary links to Versionista. With those links, they are very much a fallback, providing a temporary escape hatch that *we expect people to use less over time.* Removing it should largely be painless, because very few people should be using it much by the time we do that. With this, we’re talking about *the most heavily used feature in an analyst’s toolbox.* This is literally the first thing many people look at when going through their pages every week. Removing or fundamentally changing that kind of feature once you’ve put it in is rarely simple.

>Because of that, I think it’s really important to support what analysts want or expect this to be and not just build the technical equivalent of what is in the Versionista sheets—because I think that technical answer is probably going to become divorced from what analysts actually want out of the feature as the system evolves (e.g. bringing in a longer history with Internet Archive). I really want to avoid setting analysts up with a bad expectation or a bad feature out of the gate. Besides, one of the main vaues of having a fancy UI and a better database than a pile of spreadsheets is so that we can provide better ways to navigate through all this data.

>**Since analysts are still using the sheets to get to our UI, and since the sheets already have this feature,** I don’t think there’s any need to rush to fill it in here with something that doesn’t actually fit well.

>I really think this is exactly the sort of thing we should be talking with analysts about and not amongst the development team. Building/releasing quickly to get feedback and iterate is great, but that should still be driven by doing the initial legwork to understand where the right place to start actually is. Our tight relationship with them should be the thing that lets us not jump to easy technical answers here and instead first ask them: “what are you trying to get a sense of when you look at ‘latest to base?’” “How would that change (if at all) if ‘base’ meant a version from several years ago?” “What shortcuts to different versions (or points in time?) would be useful?” “Do you even need any shortcuts, or just a clearer way to see or call special versions as you select which ones to compare?” etc.

**Comment by Mr0grog** [comment]
@titaniumbones -

> In the long term... and seeing as it's 2018 already... there will certainly be many contrasting uses for a "base" version, and the question of which uses are most important probably should be given to users rather than devs. Maybe there will ultimately be a (session-specific? user-specific? URL-specific?) setting for this, somewhere, eventually.

**Comment by Mr0grog** [comment]
@danielballan -

>> Maybe there will ultimately be a (session-specific? user-specific? URL-specific?) setting for this, somewhere, eventually.
> 
> This seems right, @titaniumbones . I think there is a use case for:
> 
> - standard dates (i.e. start of current administration) that are configured app-wide
> - standard intervals (1 week ago, 1 month ago, 6 months ago)
> - a URL-specific set of starred Versions (equivalently, dates) that are visible to all
> - a user-specific set of favorite dates and intervals
> ...more or less in order of importance.

**Comment by weatherpattern** [comment]
Another use case (especially once annotation are recorded in app):
- last time annotated (that is reviewed) by user
- last time annotated by anyone

Definitely agree with the statement, we can also ask the analysts directly, as well as user test options in staging.)
