### ISSUE TITLE
UI breaks if a Page has no versions

### ISSUE THREAD

**Issue by danielballan** [edgi-govdata-archiving/web-monitoring-ui#174]
This came up when a import job failed between Page creation and Version creation. Console screenshot:

![broke](https://user-images.githubusercontent.com/2279598/34629490-4c7ce30a-f236-11e7-90c6-f48183185cb3.png)

The UI should probably allow for a Page with no Versions, both in the list and page detail view.

Page Detail View: Display "No Versions" in diff area
List View: Display a placeholder that notes "No Versions"? Or just don't include such Pages?

**Comment by Mr0grog** [comment]
To clarify this issue, the [`PageList` component](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/page-list.jsx#L72) expects every page record it gets to have at least one version. It’s *possible* to have a page with not versions (though we try to make sure that generally can’t happen). The UI should handle this situation gracefully by either:

- Not showing the page
- Noting that the page has no versions

We should also make sure that the [`PageDetails`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/page-details.jsx) component handles this situation, too.

**Comment by Mr0grog** [comment]
This is a real bug that needs fixing.
