### ISSUE TITLE
Don’t request diffs for PDFs

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#179]
We know we don’t yet have a differ that supports PDFs, so we should not request diffs for them (because they’ll always appear broken). Instead, we should:

- Show each PDF side-by-side for “Side-by-Side Rendered”
- Show the new PDF for “Highlighted Rendered”
- Disable all other diff types

Does that seem right? Or should we just show alternate options altogether for types that we know we can’t diff? (e.g. “Side by Side,” “Before,” and “After”)

We could also definitely do better on surfacing mime types in `source_metadata`. Or maybe make it an actual, top-level field on version objects (any thoughts there, @dallan?).

**Comment by Mr0grog** [comment]
This also goes for situation where the before/after versions are *different* mime types. This change, for example, is HTML (an error page) before and PDF after: https://monitoring.envirodatagov.org/page/4ca4bc6f-6dc2-4b01-8e7a-94d50baf276e/e053c830-029a-4925-88c2-114b370c4fcc..8c5583c7-02f2-4ee2-a495-748865dc1330

**Comment by Mr0grog** [comment]
Quick survey of file extensions (our only reliable proxy for mime types right now):

| Extension | Count  |
| :-------- | -----: |
| html      | 449437 |
| pdf       |   3892 |
| ???       |   2377 |
| wsdl      |   1689 |
| xml       |   1506 |
| ksh       |    306 |
| ics       |    257 |
| txt       |    203 |
| rss       |    118 |
| jpg       |    106 |
| obj       |     87 |
| doc       |     85 |
| zip       |     35 |
| atom      |     33 |
| xlb       |     19 |
| pwz       |     15 |
| gif       |     11 |
| rtf       |      8 |
| csv       |      8 |
| xls       |      7 |
| xlsx      |      6 |
| png       |      5 |
| docx      |      4 |
| jpeg      |      4 |
| mp3       |      2 |
| ai        |      1 |

![screen shot 2018-01-15 at 11 07 04 am](https://user-images.githubusercontent.com/74178/34957967-b7288cb2-f9e4-11e7-9322-b9b5ece2a2f3.png)

**Comment by lightandluck** [comment]
How would we find, on staging or production, versions that we could use as tests for those use cases outlined?

**Comment by Mr0grog** [comment]
I would just do what I just did above, use a quick script to roll through the API (keep paging through `/api/v0/versions` until you get to the end or as far as you want to go) to find a PDF, for example.

You could probably also just search for `*.pdf` (or `*.whatever`) in the UI, though you’d only find ones where the *URL* has the file extension, and not ones where it was only in the `Content-Type` header (hitting the API as above would fix that). You’d probably still get plenty of results to test with that way, though.
