### ISSUE TITLE
Make consistent single pages diff results (in a frame or not in a frame)

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#183]
For single page views...

The entire page scrolls (no frame) for: Highlighted text, Highlighted Source, Changes only source, Changes only text,
The results displays in a frame: Highlight Rendered, Outgoing Link.

I prefer showing these outside of a frame, so the analyst can see more of the page at one time.
Either way, it should be consistent.

**Comment by lightandluck** [comment]
Still relevant, low priority.

Does need some digging into because frames are necessary to display rendered pages
