### ISSUE TITLE
In side-by-side view, when one version is corrupt, still allow the other side to render.

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#185]
If what is happening is what I think it is, this isn't a high priority. 
In the side by side view, if one capture is corrupted, UI throws an Error:Internal Server Error.
The right side should still be able to render.

Note, this is minor because there isn't anything to compare. That said, displaying the page that is ok, helps the analyst see which capture is corrupted with additional clicking.

Reference: https://monitoring.envirodatagov.org/page/de381fe3-cdba-4097-9eb0-ea36d35c04af/eca6ab93-996a-48e7-9b10-74739fd5d83d..74438e33-d344-432a-ab22-6cb30e7262c6

**Comment by Mr0grog** [comment]
This is actually a processing issue, can you post it over there?
