### ISSUE TITLE
FERC page generated Error: Failed to fetch

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#188]
Scanner is not able to any of these pages.
Verisonista can't render the Jan 14 captures, but it can render the other captures.

https://monitoring.envirodatagov.org/page/76f6d82f-099a-48e1-93eb-569c8a0f52e9/62755593-55c8-49a6-a964-b7c7266645f3..e8532f5e-d202-4fb2-95c9-00f38949c473

https://versionista.com/74286/6216122/14285070:9444385/

**Comment by Mr0grog** [comment]
This is actually edgi-govdata-archiving/web-monitoring-db#205.
