### ISSUE TITLE
Create diff visualization for analyst use

### ISSUE THREAD

**Issue by ambergman** [edgi-govdata-archiving/web-monitoring-ui#19]
The completed [PageFreezer-Outputter](https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/17) will output information about diffs to a series of CSVs and have a column containing a link to a visualization of the diff, for analysts to use when labeling the significance of page changes.

[This module](https://github.com/edgi-govdata-archiving/pagefreezer-cli/tree/master/interface), being developed by @allanpichardo, will likely be perfect for completing this issue.

**Comment by ambergman** [comment]
Wanted to add, as I mentioned in issue #17: Would also be great to have a couple of different visualization options, perhaps a "side-by-side" or "in-line" page view for changes, but then also a "changes only" view (very useful for huge pages with only a few changes. I'll write something about that in issue #19, the visualization issue, as well.

I'll add some screenshots later, when not in transit, of what the current UI allows.

**Comment by dcwalk** [comment]
This is a pretty big task. Maybe we could break up the steps to get there into a bunch of smaller tasks. I almost think we could treat this as like a "milestone tracking issue" in the web-monitoring repo, and have bite-sized issues in here

**Comment by ambergman** [comment]
Sorry for the slow response here @dcwalk. I think this issue is a little outdated, as I think it was initially specifically about creating a new Diff View, so that we weren't just using Versionista's, for our CSV interface. This has been solved now by @lightandluck's new Diff View (an updated version of which is [mockup up here](https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues/35)). Based on that, I'd say this issue can be close.

I definitely agree that the larger questions around finalizing the UI can be managed in the overall web-monitoring repo, with specific tasks tracked here.

**Comment by lightandluck** [comment]
This issue has been broken up into smaller tasks. Per ambergman's suggestion, closing.
