### ISSUE TITLE
Add url to page title (tab label)

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#193]
- Add the page url to the head title tag, so that the analyst can identify the page  by the browser tab label.
- Also replace “web-monitoring-ui” with "Scanner"

e.g. "Scanner | energy.gov/..."

From Sara:
It would be helpful to easily disambiguate among multiple open tabs if the page title in the tab were descriptive of the page. For example, rather than “web-monitoring-ui,” the page title appearing in the tab were “web-monitoring-ui | [page title]” or “web-monitoring-ui | [page url]”. Sure, the full title wouldn’t have room to render in the tab, but enough of it would be visible so that an analyst could more readily click on a specific tab and have an idea of what tab they clicked on. (Plus, once “web-monitoring-ui” is updated to the 10-char shorter “scanner,” there’ll be even more room)

**Comment by Mr0grog** [comment]
Which is preferable?

- “web-monitoring-ui | [page title]”
- “web-monitoring-ui | [page url]”

Both are similar effort (although page title brings with it the question: is the title the one from the latest version, the “to” version in the current comparison, or the “from” version in the current comparison).

We could also stuff the dates being compared and the type of diff in there. Will never fit in the tab, but most browsers will do tooltips for the tabs and the full title will also show up when pressing and holding the back button.

**Comment by weatherpattern** [comment]
Good question. I'd say using the url is preferred, as that is how it is listed in the analyst sheets. Although unlikely, the page title has the potential of changing, which could lead to confusion.

Adding the dates is interesting, I guess that would be handy if analysts have the same url with different dates open in multiple tabs. That feels like overkill to me, but I can ask the analysts.

**Comment by Mr0grog** [comment]
I guess I’m thinking more of its utility in other contexts besides tab switching, e.g. the back button:

<img width="777" alt="screen shot 2018-01-25 at 11 15 35 pm" src="https://user-images.githubusercontent.com/74178/35428774-da4bb766-0225-11e8-9523-990d320e61b7.png">

**Comment by weatherpattern** [comment]
Thanks for talking through the options. Let me work on this, ask around, and think about this a little more. I don't think this is a critical feature request, so won't detract you any longer from your other work. I created an enhancement label, and we can finalize the solution, and figure out the right time to slip it in.

**Comment by Mr0grog** [comment]
I feel like this is a feature still worth tracking, even though it’s very low priority.

**Comment by lightandluck** [comment]
Added `never-stale` label
