### ISSUE TITLE
Add link from page details view to Internet Archive

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#196]
*(Updated 2019-06-17)*

Where possible, we should link to the original source of pages/versions from the Wayback Machine. Analysts typically include Wayback links and screenshots in their reports (partially because our tools aren’t public-access, but also because Wayback is a pretty good system of public reference in general), so having the links directly in our views would make that a lot easier for them.

We currently show links to Versionista diffs in the top area of the page details view:

<img width="1280" alt="versionista-diff-link" src="https://user-images.githubusercontent.com/74178/59625546-69040c80-90ee-11e9-9a69-dfd4aecb4d20.png">

(This is the [`VersionistaInfo` component](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/versionista-info.jsx).)

It would be great to replace that with a link to:
- Definitely: Each of the versions being compared (if those versions are from Wayback and not some other source).
    You can find the correct link in the `source_metadata.view_url` property of a link. See an API response like this for an example: https://api.monitoring.envirodatagov.org/api/v0/pages/1829df77-b37e-49dc-998b-0fc964e7f24e/versions
- Optionally: A link to the listing/calendar view of all the snapshots of the given page in Wayback. To create that link, we’ll have to compose it from the data we have available. It always looks like `https://web.archive.org/web/*/<page_url>`, e.g. `http://web.archive.org/web/*/https://www.fhwa.dot.gov/about/staff.cfm`

    This could be a simple link right next to the original URL:

    ![view-in-wayback-link](https://user-images.githubusercontent.com/74178/59626115-e7ad7980-90ef-11e9-9531-4f8e70c25cb1.png)

---

~As I’m sitting here watching the report writing training, I’m wondering if it would be a good idea to add a link to the Internet Archive history/calendar view for a page, e.g. http://web.archive.org/web/*/https://www.fema.gov/flood-insurance-reform-mapping-flood-hazards It seems like there’s typically a lot of cross-referencing/checking with Internet Archive when building a report.~

~This might just be getting ahead of ourselves. Once we start pulling in data directly from Internet Archive, would it still be useful?~

/cc @trinberg

**Comment by Mr0grog** [comment]
We use Internet Archive snapshots in a lot of reports and analysis, so this is still an incredibly useful (and not too hard to implement!) feature — we might even consider it for *all* versions, even when they weren’t originally sourced from the Internet Archive.

**Comment by SYU15** [comment]
> We use Internet Archive snapshots in a lot of reports and analysis, so this is still an incredibly useful (and not too hard to implement!) feature — we might even consider it for _all_ versions, even when they weren’t originally sourced from the Internet Archive.

Do you still feel we should add these links even to the pages that were sourced from Versionista? I am starting to look into this.

**Comment by Mr0grog** [comment]
Yes! More:

For the version-level link (the one that comes from `source_metadata.view_url`), it’s only really applicable if the source was Wayback, but that’s a version-by-version question rather than a page-level question.

For the page-level link (e.g. [`https://web.archive.org/web/*/https://climate.nasa.gov/`](https://web.archive.org/web/*/https://climate.nasa.gov/)), I think we still always want them — analysts use these to see what additional data Wayback might have about a page, even if we haven’t imported any captures from Wayback.

**Comment by SYU15** [comment]
Ok, sounds good @Mr0grog. It seems to me that there are 2 urls being passed into the view, one for each page version that's being compared (`props.to` & `props.from`). Sometimes both have `source_metadata.view_url` from Wayback, other times one (or both, possibly, though I haven't run into this this case) is from Versionista and therefore doesn't have that field. 

Am I supposed to only render `source_metadata.view_url` from the latest page version or both of them if they exist?

**Comment by Mr0grog** [comment]
> Am I supposed to only render source_metadata.view_url from the latest page version or both of them if they exist?

For both of them if they exist.

> Sometimes both have source_metadata.view_url from Wayback, other times one (or both, possibly, though I haven't run into this this case) is from Versionista and therefore doesn't have that field.

Yep, this is by design. `source_metadata` has a standard schema based on `source_type`, so you should expect different data for a `versionsta` version than an `internet_archive` one, but you should expect that same kinds of data for any two versions with the same `source_type`. It’s basically all the additional data we could get from the source that might be unique to that source or that doesn’t fit the standard page/version model.

**Comment by Mr0grog** [comment]
Fixed in #381. We forgot to make sure the commit comment was formatted correctly to auto-close this!
