### ISSUE TITLE
Make new images changes easier to see

### ISSUE THREAD

**Issue by weatherpattern** [edgi-govdata-archiving/web-monitoring-ui#204]
Low priority
(from Kendra)
Sometimes a borders around new images is hard to pick up 

In this example, the red border gets broken up.
Could there be a pink layer on top of it? 
We still pick the changes in the source views so I don't think this is a critical fix.

https://monitoring.envirodatagov.org/page/d6671efa-b085-4514-a394-fe38a562aed9/922ed6c7-526b-481d-8a37-7e5e02a89c23..841c3d81-c252-4a7e-bb6a-bc81ff35a4eb

Also Aaron found this case:
https://monitoring.envirodatagov.org/page/ebbecab1-fd6d-483d-87f0-9098c4e40739/203d59d9-2f31-4ce8-829c-36c56d65c670..c0665c35-4c11-46aa-824f-549f74d89545

**Comment by sammy1997** [comment]
@weatherpattern  What chat platform do IA developers use?

**Comment by Mr0grog** [comment]
Hi @sammy1997, we aren’t actually a part of Internet Archive at all. You should probably check out their actual GitHub org (https://github.com/ArchiveLabs) or their contact page online (https://archive.org/about/contact.php).

**Comment by Mr0grog** [comment]
@weatherpattern this issue should really be on `-processing` right now—that’s where everything about the diffed HTML lives (including styling).

**Comment by weatherpattern** [comment]
Moving to: web-monitoring-processing repo.

https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/160
