### ISSUE TITLE
Remove edgi-web-monitor-ui.herokuapp.com or replace it with a redirect

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#228]
The app running at https://edgi-web-monitor-ui.herokuapp.com/ is super out of date and no longer official (since we have *long* since switched to https://monitoring-staging.envirodatagov.org). There are still some URL in issue floating around pointing to it, so we should either:

1. Take it down
2. Replace it with a redirect to https://monitoring-staging.envirodatagov.org

**Comment by lightandluck** [comment]
I deleted the app from heroku.
