### ISSUE TITLE
move filtration issues to this repo

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#24]
`filtration` currently has filter-related issues but no code. We should move those issues to this repo & deprecate `filtration`.

**Comment by dcwalk** [comment]
We might want to contact GH support on this and see if they can complete the transfer while preserving the creation history?

**Comment by danielballan** [comment]
Agreed.

If the structure we are discussing in #29 works out, we'll probably end up with two repos related to versioning: one that is mainly processing code and one that is mainly web code, linked by an agreed upon database schema.

**Comment by dcwalk** [comment]
I've email GH support and asked if they can move the issues to `web-monitoring-processing`
 https://github.com/edgi-govdata-archiving/web-monitoring-processing/issues/1

**Comment by dcwalk** [comment]
Closing this as complete, issues were moved to edgi-govdata-archiving/web-monitoring-processing
