### ISSUE TITLE
Determine status of `page_freezer_python_module`

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#26]
@stuartlynn and @danielballan, what is the status of `page_freezer_python_module`? Should we continue to use it as a skeleton for the overall app, or discard it?

**Comment by danielballan** [comment]
I don't think @stuartlynn or I are attached to that work: we were just exploring the PageFreezer results using pandas. But let's leave it there in case we use some part of it in the skeleton of a web backend.

**Comment by stuartlynn** [comment]
Hey. I think the class we built is actually a good starting place to build some convenience methods for the API and to do some format/tracking and applying of different change stats. Happy to discuss it more but haven't had a chance to update the code since the event

**Comment by danielballan** [comment]
OK, sounds good. I'm trying to wrap my head around all of the disparate work that's been done [over here](https://github.com/edgi-govdata-archiving/pagefreezer-cli/issues/28).

**Comment by danielballan** [comment]
I'm going to close this issue. The Python module is [part of the `web-monitoring-processing` repo](https://github.com/edgi-govdata-archiving/web-monitoring-processing).
