### ISSUE TITLE
Switch MAINTAINER to LABEL directive in Docker

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#267]
We use the `MAINTAINER` directive in our docker files, but it’s been deprecated:

> The `LABEL` instruction is a much more flexible version of this and you should use it instead, as it enables setting any metadata you require, and can be viewed easily, for example with docker inspect. To set a label corresponding to the `MAINTAINER` field you could use:
> 
> ```
> LABEL maintainer="SvenDowideit@home.org.au"
> ```

- [`MAINTAINER` docs](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated)
- [`LABEL` docs](https://docs.docker.com/engine/reference/builder/#label)

**Comment by professionalzack** [comment]
working on this
