### ISSUE TITLE
Switch from Yarn to NPM

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#281]
Discussed this at today’s dev meeting — we want to keep things simple by not requiring an extra tool for dependency management. Yarn served us well, but NPM now supports the critical features we originally used Yarn for.

- Remove Yarn lockfile and add NPM lockfile
- Update README
- Update CircleCI config
- Update Dockerfile
- Update any deploy scripts/docs as needed

**Comment by Mr0grog** [comment]
I think I’m going to go ahead and do this after #306 and #305 are in.

**Comment by lightandluck** [comment]
👍🙏🏗🚀💪👍
