### ISSUE TITLE
Search in "All Pages" reverts to "Assigned Pages"

### ISSUE THREAD

**Issue by gretchengehrke** [edgi-govdata-archiving/web-monitoring-ui#288]
@lightandluck 

I'm working on a report right now and am trying to find pages that Justin Schell is monitoring in BLM. However, when I go to https://monitoring.envirodatagov.org/pages to search for the URLs, as soon as I paste in the URL I want, the screen (before I even hit "enter") automatically has the beige/yellow bar that says "You don't have any assigned pages" even though I am still on the /pages page, not the /assignedPages page.

## Expected Behavior
I would expect to be able to search for the URL since I have a UI account, regardless of whether or not I have assigned pages. Also, I have successfully searched for URLs this way before (even earlier tonight!).

## Current Behavior
Before I even complete my attempted search by hitting enter, the screen forwards to a "You don't have any assigned pages" banner, even though the URL remains on /pages. 

## Possible Solution
no idea how to fix this bug -- sorry!

## Steps to Reproduce (for bugs)
1. Using Google Chrome on Windows 10
2. Open a new tab with https://monitoring.envirodatagov.org 
3. Click on the "All Pages" button 
4. Type a URL into the "Search for a URL..." box 

## Context
I can't see the page history for this page, especially since the Wayback Machine doesn't have it in the timeframe I'm interested in, so I can't double-check Justin's work. I'm also trying to contextualize the changes, and I can't view the diffs, so it's taking a lot longer to identify the changes on the page (since Justin copied and pasted the whole page text into the Google Doc). Please do help when you can. Thank you!! 

## Your Environment
Google Chrome Version 69.0.3497.100
Windows 10 Professional

**Comment by lightandluck** [comment]
Apologies, @gretchengehrke, I was out of town this weekend. Put together a [PR](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/290/files) that keeps the search bar visible so you can refine your search when no results are returned.
