### ISSUE TITLE
Pagefreezer-api page link does not work in the README file.

### ISSUE THREAD

**Issue by sudk1896** [edgi-govdata-archiving/web-monitoring-ui#33]
The pagefreezer-api link given [here](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/pagefreezer-api.md) doesn't work (404 page not found).
I found one on the pagefreezer website given [here](https://www.pagefreezer.com/development/), although I don't know how helpful this would be and also the page is a bit dated, the API could have changed as well.
Kindly update the link. Also are there any wrappers for that API perhaps in Python/Ruby etc ?

**Comment by lightandluck** [comment]
Sorry, about that! We recently split off the UI project from the data processing project. You may be more interested in that [repo](https://github.com/edgi-govdata-archiving/web-monitoring-processing). The link you're looking for is [there](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/pagefreezer-api.md). I'll be replacing the README completely to reflect the split. 

I can't answer to your question about the API wrapper, but from what I've seen, it doesn't look like there is one. @danielballan may know better. Pagefreezers docs are lacking, unfortunately.

**Comment by danielballan** [comment]
During the NYC event, we looked for wrappers and found none. I wrote a Python function for a simple case [here](https://github.com/edgi-govdata-archiving/web-monitoring-processing/blob/master/web_monitoring/db.py#L387). Also see [here](https://github.com/edgi-govdata-archiving/web-monitoring-processing/tree/master/page_freezer_python_module).
