### ISSUE TITLE
Remove “view this diff in versionista” links

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#372]
We currently show links to diffs in Versionista when viewing versions that were sourced from Versionista:

<img width="1280" alt="versionista-diff-link" src="https://user-images.githubusercontent.com/74178/59626212-2ba07e80-90f0-11e9-8ea2-a53a5346542f.png">

**We should get rid of this:**
- Many of these no longer render a link because they are so old (Versionista only stores content for so long).
- We’ve turned off our Versionsta accounts, so these might not work anyway.
- They were meant as a helpful tool while we transitioned to analysts primarily using our tools instead of Versionista’s, and we’re long since past that point.

The source is at [`src/components/versionista-info.jsx`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/versionista-info.jsx) and it gets used from `ChangeView` here: https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/d1fb175bfd5984844322eea8111c96cbefa73ffb/src/components/change-view.jsx#L158-L160

See also #196, where we are adding Internet Archive links. Those will probably always be relevant, while these Versionista ones no longer are.

**Comment by SYU15** [comment]
Cool, will probably tackle this first then. Thanks for the background info!

**Comment by SYU15** [comment]
Or do you think I should make one PR to tackle both @Mr0grog?

**Comment by Mr0grog** [comment]
Nah, I’d do separate PRs for each, personally.

**Comment by Mr0grog** [comment]
Fixed in  #374.
