### ISSUE TITLE
Ensure links in pages don’t load inside an iframe

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#382]
If you are looking at an HTML diff right now, clicking a link navigates the frame that the diff is in. That’s really problematic, because it can be unclear that the view you are looking at is:
- No longer related to all the metadata surrounding it in the view.
- No longer even a diff.
- In a side-by-side diff, it’s not even the same URL/page as the other side.

Instead, we should be handling link clicks specially. If the link changes more than just the URL hash, we should either:
1. Open it in a new tab.
2. Open the target of the link in the Wayback Machine in a new tab.
3. If we have the target URL in our database, open the diff of *that* page for the same/similar timeframe as the current view. (To do this well probably requires some kind of canonical URL querying in the `-db` project, which is a lot of extra effort.)

(3) would be pretty awesome, but I think is complicated. For now, I think (1) or (2) is a good approach.

This issue is port of edgi-govdata-archiving/web-monitoring-processing#96 — for the way we are set up now, it’s more relevant to do the work here in `-ui`.

**Comment by Mr0grog** [comment]
To do option (1) or (2), you should be able to:

1. Add a new transform function to [`src/scripts/html-transforms.js`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/scripts/html-transforms.js) that modifies all links in the page (or possibly that adds a script that pre-empts clicks). Transforms are functions that take a DOM `Document` object and return an edited version or copy of the document. See `removeStyleAndScript` for an example: https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/403c46435e970afbd414aec7b93cc0224a15af3b/src/scripts/html-transforms.js#L14-L29

2. Call that transform from the diffs where it’s relevant, e.g. https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/403c46435e970afbd414aec7b93cc0224a15af3b/src/components/side-by-side-rendered-diff.jsx#L26-L40

**Comment by professionalzack** [comment]
@Mr0grog I am interested in trying this out, but haven't seen links in diffs yet. Do you have any examples of this issue so I can attempt to replicate? Thanks!

**Comment by Mr0grog** [comment]
We found some while working in person, but if anyone else needs a quick example here, try this URL from our staging database:

https://monitoring-staging.envirodatagov.org/page/17cecc12-cdcd-4840-8100-e191ed37d226/2dfe989e-c571-40b0-8b25-ce8a3c5f630a..56c6d61e-36f5-4c33-8096-4da3c58484e6

Or if your local install is set up read from staging (that’s the default setup), you can use this URL to test locally:

http://localhost:3001/page/17cecc12-cdcd-4840-8100-e191ed37d226/2dfe989e-c571-40b0-8b25-ce8a3c5f630a..56c6d61e-36f5-4c33-8096-4da3c58484e6

**Comment by Frijol** [comment]
This appears to be already implemented – can we close it?

**Comment by Mr0grog** [comment]
Argh, I thought this got closed as part of #405. Yes, it should not still be open.
