### ISSUE TITLE
Add linter

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#39]
Add linter to project to maintain code consistency. Follow EDGI [guidelines](https://github.com/edgi-govdata-archiving/overview/blob/ce56269a111b2d733f42a98ca54e525b03ddd6f7/protocol/linting.md)

**Comment by dcwalk** [comment]
Yeeeeaaah! I think this obviously depends on the framework per #41, but I think could be something moved on fairly quickly?

**Comment by lazywithclass** [comment]
I had a go at this, after running `gulp` I got 

> [09:56:03] Finished 'watch' after 7.03 ms
>events.js:160
>      throw er; // Unhandled 'error' event
>      ^
>TypeScript error: node_modules/@types/core-js/index.d.ts(39,27): Error TS2304: Cannot find name 'IterableIterator'.

Anyway, I don't think that's going to affect this work, so I just proceeded adding the linter.

Please find the PR [here](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/47), let me know if you would like me to change something.

**Comment by Mr0grog** [comment]
This was resolved as part of #48.

**Comment by lazywithclass** [comment]
:+1:

**Comment by Mr0grog** [comment]
@lazywithclass sorry for the crossed wires with this and #48. I don’t know if you saw my comment: https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/47#issuecomment-303785941, but we’d still love help if you’re interested in working on this project :)

If you have any strong feelings for or against Typescript, too, we’d love any feedback on #53.

**Comment by lazywithclass** [comment]
@Mr0grog I am willing to contribute, at the time of this small PR I registered on Slack but couldn't really find somethiing to help with, do you have any suggestion?

**Comment by Mr0grog** [comment]
@lazywithclass more than anything, join in on n the community call today if you can at 6:30 ET.

We also have some issues tagged `mozsprint` for people to work on today and tomorrow: https://github.com/edgi-govdata-archiving/web-monitoring-ui/issues?q=is%3Aissue+is%3Aopen+label%3Amozsprint

Adding some starter tests is also good; I'm going to pick it up soon if nobody else does: #52 (FWIW, I was going to do unit tests w/ Mocha & Karma, but am not opposed to most other tools—except maybe Jasmine).
