### ISSUE TITLE
Remove “Assigned Pages” View

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#394]
We should remove the “assigned pages” view. It:
- Isn’t actively used by analysts,
- No longer accurately reflects how we manage tasking for analysts, and
- Adds a fair amount of complexity to our API. For example, most of `src/services/web-monitoring-api.js` is dedicated to it: https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/403c46435e970afbd414aec7b93cc0224a15af3b/src/services/web-monitoring-api.js#L61-L87

---

Things that should be removed/cleaned up:

- [x] Remove all the complex data loading logic around asssigned pages in [`src/components/web-monitoring-ui.jsx`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/web-monitoring-ui.jsx) (There’s not actually a special component for it, just different data in the `PageList` component.)

- [x] Remove nav links https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/403c46435e970afbd414aec7b93cc0224a15af3b/src/components/nav-bar.jsx#L23

- [ ] Remove parts of [`src/services/web-monitoring-api.js`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/services/web-monitoring-api.js#L61-L87) that are no longer relevant (we still need some of it for saving important changes to Google Sheets).

- [ ] Remove web server parts that are no longer relevant (i.e. the parts with correspond to what needs removing from `src/services/web-monitoring-api.js`: https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/403c46435e970afbd414aec7b93cc0224a15af3b/server/app.js#L92-L105 and other files in `server/`

**Comment by SYU15** [comment]
Cool, I'll start taking a look into this, might have some questions about whether or not I'm ripping out the right stuff.
