### ISSUE TITLE
Migrate CSS for login-form component

### ISSUE THREAD

**Issue by SYU15** [edgi-govdata-archiving/web-monitoring-ui#406]
Right now the CSS for this component lives in `styles.css`:
https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/css/styles.css#L436

This is vanilla CSS that is currently loaded at the global level but we are currently migrating our CSS to [CSS Modules](https://github.com/css-modules/css-modules).

Here is an [example PR](https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/393) where the `source-info` component was migrated over.

To accomplish this we need to do the following:

1. Add the CSS to the new pipeline by migrating it out of `styles.css` and into a new file called `login-form.css`. The directory structure should look like this:
```
src/components
└─┬ login-form
  ├── login-form.jsx
  └── login-form.css
```

2. In `login-form.jsx`, the new CSS file needs to imported:
```
import './login-form.css';
```

3. The `.login-form h1` and `.login-form .form-group` selectors need to be refactored to be a single class name. Something like `.login-form-title` and `.login-form-group` could work or something similar. These classes need to be added/replaced in the `login-form.jsx` file. Feel free to ask if you aren't sure where the new classes should go in the markup.

4. In `login-form.jsx`, the `className` tags needs to be added or replaced for `styleName` **for the component level styles only**. Global styles should stay in `className` tags and a component can have both `className` and `styleName` tags at the same time if necessary. Feel free to ask if you aren't sure if a style falls under either category. (This basically determines which classes get suffixed with a hash to make sure it is scoped at the component level).

Here is an example of `styleName` vs `className` being used in our codebase:
https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/06faddae40f19eb7785e87ffc2d33055500f2658/src/components/source-info/source-info.jsx#L65-L73

**Comment by mastal88** [comment]
Hi,
I'd like to contribute to solving this issue, but I'm getting errors from lint during commit

> eslint --ignore-path .gitignore './**/*.{js,jsx}'
>
>
>Oops! Something went wrong! :(
>
>ESLint: 6.3.0.
>
>No files matching the pattern "'./**/*.{js,jsx}'" were found.
>Please check for typing mistakes in the pattern.

Could you help me with that?

**Comment by Mr0grog** [comment]
Hi @mastal88, what does your directory & file structure look like, and where are you running `git commit` from?

**Comment by mastal88** [comment]
Hi @Mr0grog,
I haven't change the file/directory structure and I'm running git commit from the project folder - so basically what I've done:

- forked the repo

- git clone of my forked copy

- cd into project folder

- npm i

- npm run lint (and it ends with this no files found error)

**Comment by Mr0grog** [comment]
Hmmmm, I can’t reproduce this. Would you please open a separate issue and include what OS, Node.js version, and NPM version you are using or hop on [Slack](https://github.com/edgi-govdata-archiving/web-monitoring#get-involved) to discuss it?
