### ISSUE TITLE
Administration views and workflow

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#42]
Dependent on #35. When workflow is approved this will need to be mocked up and coded.

**Comment by lightandluck** [comment]
For v0 we will likely implement this using Google sheets, so that we can easily reassign sites to analysts.

**Comment by lightandluck** [comment]
Realized this issue is too broad. Breaking out tasking into it's own issue.

**Comment by Mr0grog** [comment]
(That issue is #78)

**Comment by Mr0grog** [comment]
Since #78 is done, I think we need to enumerate here exactly what else we need/want to support in this vein or close this issue for now.
