### ISSUE TITLE
Add loading state for when search queries are being fetched

### ISSUE THREAD

**Issue by SYU15** [edgi-govdata-archiving/web-monitoring-ui#436]
As our search functionality expands, it will be good to give the user feedback as we are fetching search results to avoid preemptive cancellation/modification of queries and such. Maybe some kind of overlay over the page results would be nice?

**Comment by johnsonphan95** [comment]
I can go ahead and try to work on this, I've gone ahead and recycled the infinity loop loading animation on my local branch.

**Comment by SYU15** [comment]
That would be amazing if you could do that. Thanks @johnsonphan95!

**Comment by Mr0grog** [comment]
Fixed in #440.
