### ISSUE TITLE
Incorporate services from processing and diff projects to create a diff view

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#44]
We need to look at work done in web-monitoring-processing and differ to see what can be incorporated in the app to actually visualize diffs. Currently the app only receives versionista links from web-monitoring-db, which are not embeddable, so users still have to click out to another website.

**Comment by danielballan** [comment]
Any ideas for where it would be easiest to start, on your side? For example, presenting the full HTML of each side by side?

**Comment by danielballan** [comment]
Just to update anyone who reads this issue later, the web-monitoring-db app will have diff-related endpoints (one for UNIX-style text diff, one for PageFreezer style JSON response, potentially others in the future) that the UI can use. The -db will broker the diffs from other services (a work-in-progress in web-monitoring-processing repo).

**Comment by Mr0grog** [comment]
> For example, presenting the full HTML of each side by side?

Oh, this **is** probably a good (and relatively easy) place to start. The API should already provide everything necessary for it. :+1:

**Comment by lightandluck** [comment]
Good idea, we can run them through PF for demo purposes too, if that's still around. Can someone pm me the key, if that sounds useful?

**Comment by danielballan** [comment]
The PF requests are taking on average ~10 seconds to process via the public API so maybe better to wait until we can thread them through the -db app -- with our special access via the Google Cloud deployment and/or caching. I'll PM you the key so you can play around though.

**Comment by Mr0grog** [comment]
Oh no, not sure how I wound up creating #60, which is definitely a dupe of this. That one is a little more concise and clear with respect to what the DB has available now, though, so I'm closing this one instead.
