### ISSUE TITLE
Error handling for React app

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#50]
After the migration, the basic React app will need better error handling. As of now, it just goes on the assumption that everything works.

**Comment by KrzysztofMadejski** [comment]
+1, if for example DB throws errors (https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/81) then UI doesn't take that into an account.

**Comment by Mr0grog** [comment]
**TODO: Need someone to run through and catalog places in UI where errors aren’t handled.** Post back here as a checklist.

**Comment by dphiffer** [comment]
Took a first shot at this: https://github.com/edgi-govdata-archiving/web-monitoring-ui/commit/bf3c52a894be5dda608de2268842d1e166c67ae7

<img width="533" alt="screen shot 2018-01-10 at 8 31 25 pm" src="https://user-images.githubusercontent.com/38114/34804197-45d936bc-f645-11e7-94f9-99b197814529.png">

The error in the screenshot makes me think there may be a need, on the db side of things, to implement some kind of API throttling when it tries to hit the Google Sheets API.

**Comment by Mr0grog** [comment]
This looks great! I made some notes on your issue about sheets, but just to re-iterate, that part is fully contained in the UI project and doesn’t actually have anything to do with DB  😬

**Comment by dphiffer** [comment]
Oh you're right, it's hitting the local API and not the db.

**Comment by Mr0grog** [comment]
No, just close.
