### ISSUE TITLE
Open page details in new tab when cmd/ctrl+clicking on rows in page-list

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#505]
In most browsers, holding the cmd/ctrl key when clicking a link opens the link in a new tab/window. It would be great if that worked with the rows in [`PageList`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/page-list/page-list.jsx).

This mainly means checking the keys on the event object in `didClickRow`: https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/d0703d50e08341ff4e84ad1376612e87be4d4240/src/components/page-list/page-list.jsx#L98-L105

**Comment by SYU15** [comment]
Closed via #506
