### ISSUE TITLE
Add tests! (And turn on CircleCI)

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#52]
I failed to get this done as part of #48, but we should set up:

- Unit tests
- Integration/browser tests
- CircleCI support for the above

**Comment by lazywithclass** [comment]
@Mr0grog I followed the README but I am getting

```
GET http://web-monitoring-db.dev/api/v0/pages net::ERR_ICANN_NAME_COLLISION
```
and

```
TypeError: Failed to fetch
```

in the console, I am probably doing something silly. For example:

 * do I have to start the other two projects in order to see this one running ok?
 * is it ok to not change anything in .env?

Thanks and sorry if I missed something crucial

**Comment by Mr0grog** [comment]
Oh, you should not have:

```sh
WEB_MONITORING_DB_URL=http://web-monitoring-db.dev
```

In your `.env` file unless you actually have a server running there. If you specify nothing, you get the staging server (which is `https://web-monitoring-db-staging.herokuapp.com`), or you can set it to the production server (`https://web-monitoring-db.herokuapp.com`).

We should probably change the URL in the example `.env` file to point to staging, sorry :\

**Comment by lazywithclass** [comment]
Thanks for the prompt answer! That was it, I can work on the issue now.

**Comment by lazywithclass** [comment]
https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/70
