### ISSUE TITLE
More Meaningful Buttons in "Page Changes" view

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#59]
The current UI reproduces our legacy system of **numbered change categories** for page diffs. This has the advantage of continuity for our existing analysts, but is puzzling and a barrier to entry for anyone else. Our UI allows uders to toggle category definitions, but this seems to me to toggle between too little and too much information. Can we make this process more accessible by **switching from checkboxes to buttons**; buttons could contain abbreviations or emoji, as well as tooltips for more detailed explanations? 

There is also maybe a bigger conversation about this system -- do analysts really use all these categories? @trinberg @ambergman thoughts?

**Comment by patcon** [comment]
:+1: to emoji! :)

**Comment by Mr0grog** [comment]
I’m not sure checkbox → button is an improvement—if someone accidentally or spuriously clicks a button, then we have give them a way to reverse the action (and from a user perspective, almost any choice on how to do so will be less clear and obvious than a checkbox or some kind of toggle switch).

Totally with you on the labels. I feel like reproducing the current naming system is the right place to start, though—we don’t to throw people into both a totally new UI for navigating **and** a different set of categories/names for classification. That is, I think it’s important to stick with these labels for the first version analysts actually start to use, then we should begin to migrate to something that takes better advantage of how we can display things in the UI.

Tooltips are awesome and we can even do those immediately. I think we can absolutely reduce the amount of training necessary with tooltips or toggleable help and descriptions—and even address questions analysts who have been through training have.

**Comment by Mr0grog** [comment]
Also worth noting: as we improve here, having a UI and a database and a custom display *also* lets us do more than just checkbox/toggle-style on/off fields: we can have select lists or text fields or who knows what else.

I know a lot of these fields (in spreadsheet land) are currently meant to be filled in as:

- `0`, meaning “no” or “not significant,” etc.
- `1`, meaning “sort of” or “maybe”
- `2`, meaning “yes” or “significant,” etc.

That could easily be translated into a three-state switch with clearer labels.

**Comment by Mr0grog** [comment]
@trinberg @ambergman is the above three-state situation right? Seems like, actually, checkboxes can’t model the results we want right now, anyway.

**Comment by titaniumbones** [comment]
> I’m not sure checkbox → button is an improvement—if someone accidentally or spuriously clicks a button, then we have give them a way to reverse the action (and from a user perspective, almost any choice on how to do so will be less clear and obvious than a checkbox or some kind of toggle switch).

I was imagining a toggle that's sort of button shaped. like http://www.bootstraptoggle.com/ or something.

> Totally with you on the labels. I feel like reproducing the current naming system is the right place to start, though—we don’t to throw people into both a totally new UI for navigating and a different set of categories/names for classification. That is, I think it’s important to stick with these labels for the first version analysts actually start to use, then we should begin to migrate to something that takes better advantage of how we can display things in the UI.

right.  And I guess the current naming system is actually just a set of integers! so, maybe chunky integer-labeled toggles with explanatory tooltips? 

At some point we might be able to use emoji or color-coding as a more powerful visual cue --  for me, the integers aren't helpful, but it may be that after 90 minutes of analysis work you figure them out.

**Comment by Mr0grog** [comment]
Can we close this?

**Comment by lightandluck** [comment]
Yea, fixed via #92
