### ISSUE TITLE
Display diffs on page details view

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#60]
In the page details view, we have a “Diff to be displayed here” placeholder. Now that the database API has a way to get diffs, we should start showing them in the UI.

More on the new diff API: https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/60

**Comment by Mr0grog** [comment]
Some bits that have been rolling around in my brain that others thinking about this may not have thought through:

We’ll ideally want to display diffs & version content in an `<iframe>`, but not as merely pointing to some URL elsewhere on the web. This means that the implementation in React will be a bit more complicated.

- We’ll need to use React `ref` to get a handle on the `<iframe>` so we can fiddle with its content: https://facebook.github.io/react/docs/refs-and-the-dom.html
- Once we actually have that ref, mess with the frame’s `contentDocument` in `componentDidMount()`. See also this old code this is temporarily floating around in the `diff-view` component: https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/src/components/diff-view.tsx#L17-L35
- Also implement `shouldComponentUpdate()` to ensure that we rarely really trash and re-build the `<iframe>`.

**Comment by lightandluck** [comment]
Did we ever get the pdf diff code from that person from Mozilla Sprint?

**Comment by Mr0grog** [comment]
No, and unfortunately I lost track of it and didn't keep n touch on it for the last two weeks :(

I was just thinking about it yesterday and pinged them: https://github.com/edgi-govdata-archiving/web-monitoring/issues/36

**Comment by lightandluck** [comment]
I found this [article](https://medium.com/@ebakhtarov/handling-of-iframes-in-react-f038be46ac24) that might be useful for dealing with iframes.

**Comment by neiljp** [comment]
Hi @lightandluck & @Mr0grog, just noticed this and wanted to check what the status was before returning to this.

**Comment by danielballan** [comment]
Welcome back, @neiljp. You can base your work off of https://github.com/edgi-govdata-archiving/web-monitoring-ui/pull/82, which is a work in a progress but a big step forward from the current master branch.

**Comment by Mr0grog** [comment]
This was solved in #82. Closing.
