### ISSUE TITLE
Add classifications to change

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#62]
The analyst team uses a detailed set of classifications for diffs (about 20 categories). We need to replicate this list to achieve parity with the current system. 

We may eventually want to make this taxonomy team-specific, in much the same way that issue labels can be specified in Github organizations?

**Comment by Mr0grog** [comment]
This exists and works; closing. If we have more specific changes to annotations, we should handle each of those as new, separate issues at this point.
