### ISSUE TITLE
"Remove Formatting" checkbox does not remove stylesheet `<link>` elements with multiple `rel` values

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#658]
Some pages load external stylesheets with `<link>` elements that have *multiple* `rel` values (`rel` is a `DOMTokenList`, not a single string). When pages do that, we fail to remove their stylesheets!

For example, try checking the “remove formatting” checkbox on this view: https://monitoring-staging.envirodatagov.org/page/6da848ce-fe21-40e2-a3d4-5d8a72029bf9/583d6eda-dc41-41f5-afc0-a71d41da8aea..18bd5bbc-ceda-48ad-b66b-867161394480

The link elements here look like:

```html
<link href="/TemplatePackage/4.0/assets/css/app.min.css?v=20-11-02T19:44:43Z" rel="stylesheet prefetch">
```

The issue is that, in the `removeStyleAndScript` transform, we only look for `<link>` elements that specify *only* `stylesheet`:

https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/2fe84a0c4a351169279066f3103fd4eca9d7717f/src/scripts/html-transforms.js#L34-L43

Instead, where need to look for elements where `"stylesheet"` is one of the values in `rel`.

**Comment by anuragb26** [comment]
Hi,
I would like to work on this issue.
Can you please assign this to me ?

**Comment by Mr0grog** [comment]
Great, thanks! You are assigned. :)
