### ISSUE TITLE
Add "team" concept to UI, db

### ISSUE THREAD

**Issue by titaniumbones** [edgi-govdata-archiving/web-monitoring-ui#66]
Several of the features requested by the analysts are heavily tied to a "team" concept -- with tasks and roles assigned to team members. Cf. #61, #62, #65.  We should evaluate whether it's worth building this concept into our design, or if it's too much work/overhead at this pressing stage of development.

**Comment by Mr0grog** [comment]
@titaniumbones can we close this? The specific issues referenced here are all complete (except backlog, which I don’t actually think is particularly “team-y”). Otherwise, this issue feels pretty fuzzy and we should try make it a bit more concrete.

**Comment by lightandluck** [comment]
Closing.
