### ISSUE TITLE
Reusable JS script to insert banner to denote app is experimental or deprecated, etc

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#67]
The UI is undergoing a lot of changes at the time. It would be nice to have a script that could add a banner denoting that a certain stage is experimental, deprecated, pointing to staging data, live data, etc. And just as easily removed when those demarcations are no longer needed.

**Comment by lightandluck** [comment]
Another use case here: https://github.com/edgi-govdata-archiving/web-monitoring-db/issues/67

**Comment by dndodson** [comment]
Hi @lightandluck, I had Jury Duty today, AKA sit and wait pointlessly, so I used some time to mock up a dismissible warning banner. There's a lot I don't know about the data and what metadata is available via the API, so for demonstration this just does a string search of the API URL. Could be extended to be more intelligent.  I am not quite sure how the frontend should determine cases like "stage is experimental, deprecated, pointing to staging data, live data, etc" but this should be adaptable to handle such cases, with extra props passed. Pushed to a new branch at https://github.com/edgi-govdata-archiving/web-monitoring-ui/commit/cfc3d0a80225bb0953b3985a0952c367798819e0

**Comment by Mr0grog** [comment]
Ohhhhh, I wasn’t actually thinking about the API in this at all when we originally proposed it (just about the UI itself), but pulling that info in is awesome (and probably much more important that which UI you are looking at) 👍👍👍

Should we try and show both here? Does that make sense, or is it too confusing?

I think examining the URL works great for now (to do better, we’d have to make some changes over on the DB side, which might also be a good idea in the future). That said, you might be able to make the URL-based check a little more generic:

```js
const environment = (this.props.apiUrl.match(/api-([^.]+)/i) || [])[1];
```

We could also do this check [server-side](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/server/configuration.js#L49-L56) so it gets injected in [`window.webMonitoringConfig`](https://github.com/edgi-govdata-archiving/web-monitoring-ui/blob/master/views/main.html) if we wanted to streamline the client code. That’s how I was thinking the UI’s environment (as opposed to API environment) would get set (by reading `NODE_ENV` or some other env var on the server and injecting it there).

Last note: does it need to be dismissible? In my head, I was thinking it wouldn’t be (so you and anyone looking at a screenshot, for example) can never forget you aren’t looking at production. Totally open to counter-arguments, though.

**Comment by Mr0grog** [comment]
> does it need to be dismissible?

That said, this is lovely functionality for other kinds of out-of-band alerts/warnings/feedback we might want to have :)

**Comment by Mr0grog** [comment]
@dndodson I know you’ve had to move in to some other things; were you planning to submit this as a PR or should someone else take this over? Thanks for the basic code you’ve proposed here, either way!

**Comment by dndodson** [comment]
Yes, I had been meaning to tweak and create a PR. Apologies for the delay. I just did so with #195. 

I used your suggestion of grabbing the environment name from the API url, and disabled the dismiss function, though I left the code there since I can foresee that being desirable for other use cases.
