### ISSUE TITLE
Errors when attempting to view diffs

### ISSUE THREAD

**Issue by tosfan4ever** [edgi-govdata-archiving/web-monitoring-ui#68]
So after I hit "Last 2 diff" or "Last to base Diff" for any of the sites, the following error page keeps popping up for me:

![screen shot 2017-06-02 at 1 08 21 pm](https://cloud.githubusercontent.com/assets/12403634/26736589/c6b692d0-4794-11e7-9cd3-ea60a66d6817.png)

**Comment by Mr0grog** [comment]
Yeah, you have to be logged into Versionista for this to work. We are also working on generating our own diffs so people don’t have to be trusted with login credentials:

- https://github.com/edgi-govdata-archiving/web-monitoring-db/pull/60
- https://github.com/edgi-govdata-archiving/web-monitoring/issues/12
- https://github.com/edgi-govdata-archiving/web-monitoring/issues/36

But for now, only a small pool of people have right to view what's on the other side of those two links, which is unfortunately necessary :\

What you *would* see here is a screen noting the to versions you are looking at with a dropdown that lets you select the *kind* of comparison to view (source with changes highlighted side-by-side, same with changes integrated in a single view, readable text with changes highlighted side-by-side, same with changes integrated into a single view, a normal view of each version of the page as you’d see it in the browser side-by-side, same with changes highlighted)

**Comment by tosfan4ever** [comment]
May I please be given the login credentials then?

**Comment by Mr0grog** [comment]
I can’t give you those, but here are some example screenshots:

![screen shot 2017-06-02 at 10 16 40 am](https://cloud.githubusercontent.com/assets/74178/26736936/f0bc4380-477c-11e7-90bf-90f5a5aec3db.png)

![screen shot 2017-06-02 at 10 17 46 am](https://cloud.githubusercontent.com/assets/74178/26736938/f0bfc4a6-477c-11e7-84e5-1170aa050fa0.png)

![screen shot 2017-06-02 at 10 18 09 am](https://cloud.githubusercontent.com/assets/74178/26736937/f0bf276c-477c-11e7-802a-489ae54a3e6a.png)

**Comment by tosfan4ever** [comment]
Okay sure thing, thank you!

**Comment by Mr0grog** [comment]
(Those login credentials control paid accounts, hence the concern about wide sharing)

**Comment by tosfan4ever** [comment]
Understood!
