### ISSUE TITLE
Add watchify + errorify to gulp so that errors don't break watch task

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#71]
Right now, syntax errors break the gulp watch task, which is annoying to have to recognize and restart. We should incorporate the above plugins to have a better alert system for errors and not break the watch task.

[watchify](https://github.com/substack/watchify)
[errorify](https://www.npmjs.com/package/errorify)

**Comment by KrzysztofMadejski** [comment]
Gulp-watch recommends using plumber [to catch errors](https://github.com/floatdrop/gulp-watch/blob/master/docs/readme.md#prevent-pipe-breaking-on-errors). How about using it?
