### ISSUE TITLE
Allow analysts to filter versions by custom date ranges

### ISSUE THREAD

**Issue by lightandluck** [edgi-govdata-archiving/web-monitoring-ui#81]
At present, the list view just looks for versions created over the last 3 days when presenting the list of versions as a quick way to filter the information. Ideally, we should allow them to search across any range or allow admin to set a range.

This should probably be near or part of the URL search bar at the top of the list view. We could start with a first PR that simply adds from/to or after/before fields, and then a second PR with some sort of nice date picker UI to make it easier to use.

*(Updated 2019-06-17 by @Mr0grog)*

**Comment by Mr0grog** [comment]
So much needs to be re-worked on the list view. This should not be closed.
