### ISSUE TITLE
Remove jQuery and Bootstrap

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ui#87]
**(This should wait until after V0 is done)**

We aren’t using Bootstrap’s features very extensively and otherwise have no need for jQuery (since we are using React), so I think it would be a good idea to remove these two dependencies.

**Comment by Mr0grog** [comment]
This is still important cleanup!

**Comment by steryereo** [comment]
I'm planning on working on this issue and I've been looking at what would be necessary for this migration. I think the simplest way to remove these dependencies without changing the project visually would be to create a new file like `base.css` or `shared.css` and copy the necessary bootstrap styles into it (mostly things like alerts, buttons, and form elements). I would probably opt for still bringing in normalize.css unless there are any objections.

However, as long as base styles are being rooted out, it might also be a good inflection point for adopting any sort of changes to the underlying aesthetic,  layout/grid system, etc. I'm new here and don't really have an opinion, but I wanted to open it up for discussion in case anyone was thinking along these lines.

If anyone has feedback on any of this, it's much appreciated!

**Comment by Mr0grog** [comment]
> It might also be a good inflection point for adopting any sort of changes to the underlying aesthetic, layout/grid system, etc.

I think it’s wise to keep the changes relatively minimal here (fine if there are small aesthetic tweaks). Bigger design changes would be very welcome, but are a whole can of worms on their own with a lot of discussion. What I’d like to focus on *here* is removing a dependency that makes design/style changes harder to implement or understand. Let’s get [most of] the CSS all coming from the same system.

> I think the simplest way to remove these dependencies without changing the project visually would be to copy the necessary bootstrap styles into `global.css` (or make a new non-global css modules file, name it something like `base.css` and use [named styleName resolution](https://github.com/gajus/babel-plugin-react-css-modules#named-stylename-resolution) where necessary).

I think it’s important that we don’t just move the relevant styles into a new global location — the benefit here is less about not depending on Bootstrap than it is about styles coming from the same place system and working in a cohesive way.

`base.css` with named resolution is great wherever it makes sense, but we should also take care to do something else where it doesn’t. E.g. rather than adding global modal styles to `base.css`, we should wrap `<AriaModal>` in a new modal component that adds appropriate styles to the `<AriaModal>`.

> I would probably opt for still bringing in normalize.css

Agree, seems like a good idea to keep!
